export const articles = [
  {
    id: 1,
    title: 'Cognitive Load: The Hidden Study Advantage',
    author: 'Derek Turso',
    readTime: '3 min read',
    date: 'June 25, 2025',
    icon: '/images/article-icons/icon1.svg',
    cardImage: '/images/articleicons/images (2).jpg',
    excerpt: 'A practical guide to why thinking harder while studying builds stronger memory and better grades.',
    content: [
      { type: 'paragraph', text: 'Imagine you are a student in school that aims to get the grades they’ve always deserved. Putting in hours on hours in hopes that you perform well on your tests.' },
      { type: 'paragraph', text: 'You slowly become burnt out, begging that in some way you can speed up the process of studying while still achieving grades you know you can get.' },
      { type: 'paragraph', text: 'I’ve got the solution to that.' },
      { type: 'paragraph', text: 'A little-known principle that stands as the backbone for most of the learning seen in top students today.' },
      { type: 'heading', text: 'What is Cognitive Load, Exactly?' },
      { type: 'paragraph', text: 'Cognitive load is the total amount of mental effort used in your memory while learning. It’s a core principle in educational psychology, helping explain why some study methods are more effective than others.' },
      { type: 'paragraph', text: 'Your memory, at its base level, is just the organization of how your 86 billion neurons connect to one another.' },
      { type: 'paragraph', text: 'These connections between neurons are referred to as synapses, which your brain contains roughly 100 trillion of.' },
      { type: 'paragraph', text: 'This seemingly infinite network is the true backbone of the memories we maintain throughout our lives.' },
      { type: 'paragraph', text: 'Think of your brain like a muscle, like any other one in your body. As your muscles receive a stimulus, they adapt, growing stronger and more capable.' },
      { type: 'paragraph', text: 'The same thing occurs in your brain.' },
      { type: 'paragraph', text: 'As your brain uses more resources to solve problems, cognitive load increases, causing the synapses in your brain to develop and grow stronger, becoming more capable of receiving the signals which facilitate our memory.' },
      { type: 'heading', text: 'How do we “train our brains” this way?' },
      { type: 'paragraph', text: 'By finding methods of learning that develop the synapses of our brain.' },
      { type: 'paragraph', text: 'One of the most common ways to do this is by understanding information at a deeper level.' },
      { type: 'paragraph', text: 'Instead of just reading something, ask yourself the question “what did I just read”, or “what does this mean” without looking back at the text.' },
      { type: 'paragraph', text: 'Oftentimes, this seems hard at first. However, that is the golden formula to learning better over time.' },
      { type: 'paragraph', text: 'Experiencing these “harder” methods of learning and understanding give our brain the stimulus it needs to develop stronger neural connections and synapses.' },
      { type: 'paragraph', text: 'This process is often referred to as synaptic plasticity, or the changing of the synaptic structures that our memory is based on.' },
      { type: 'paragraph', text: 'This is why it is better to take a practice test on the notes you have instead of just reading your notes over, because taking a practice test uses more brainpower than simply rereading notes.' },
      { type: 'paragraph', text: 'Think about it like this: reading is like watching someone lift weights. Practice testing is like lifting the weights yourself.' },
      { type: 'paragraph', text: 'Another method that promotes cognitive load is the Feynman technique.' },
      { type: 'paragraph', text: 'By simplifying information and pretending to teach it to someone younger—like a 5th grader—you’re forced to process the material at a much deeper level.' },
      { type: 'paragraph', text: 'We think we know something just because we can recite the fact, but often being able to synthesize the information becomes more important, as not all tests are just reciting facts.' },
      { type: 'paragraph', text: 'All of these methods challenge your brain to think deeper about the material, and not just see it at face value.' },
      { type: 'paragraph', text: 'By allowing your synapses to adapt and become more efficient, the brain can fire off neural signals more quickly, providing the boost in memory that is necessary for doing well in school.' },
      { type: 'heading', text: 'The Downsides…?' },
      { type: 'paragraph', text: 'It seems like a perfect paradise, right? The perfect principle to boost your memory forever? Not exactly.' },
      { type: 'paragraph', text: 'Like with weightlifting, using insanely heavy weights often does not provide the growth that an adequate amount of weight would.' },
      { type: 'paragraph', text: 'The same principle applies here.' },
      { type: 'paragraph', text: 'Utilizing a heavier cognitive load than appropriate often decreases the performance of one’s brain.' },
      { type: 'paragraph', text: 'However, the methods of learning that are often heralded as great (like the ones I mentioned above) sit comfortably at the top of the curve, at the sweet spot.' },
      { type: 'image', src: 'https://substackcdn.com/image/fetch/$s_!oNXK!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0cd8ea6e-dffb-4b60-96c5-ec7a8cbeb643_1647x1090.png', alt: 'Study and cognitive load visualization' },
      { type: 'heading', text: 'The Farewell' },
      { type: 'paragraph', text: 'Like we said earlier, it is important to use techniques that have higher cognitive load as opposed to techniques that are passive and use little brainpower.' },
      { type: 'paragraph', text: 'Ultimately, the development in memory that occurs is stronger, lasts longer, and has more depth than memory acquired through passive learning methods.' },
      { type: 'paragraph', text: 'So next time you\'re studying, don’t just review—wrestle with the material. Teach it. Quiz yourself. Push your brain just enough. That’s how strong memory—and strong grades—are built.' },
      { type: 'quote', text: '—The Study Mission' },
    ],
  },
  {
    id: 2,
    title: 'Spaced Repetition: Stop Cramming, Start Spacing',
    author: 'Derek Turso',
    readTime: '2 min read',
    date: 'July 7, 2025',
    icon: '/images/article-icons/icon2.svg',
    cardImage: '/images/articleicons/timeline-symbol-icon-shadow-timeline-symbol-icon-shadow-simple-vector-logo-435329456.webp',
    excerpt: 'Why spacing out review beats marathon cramming sessions and how to implement it.',
    content: [
      { type: 'paragraph', text: 'Day in and day out, our brains slowly forget everything they’ve ever learned. The information we cherish dearly slips away from our fingertips, to never be seen again.' },
      { type: 'paragraph', text: 'You watch as the key things you worked hard to memorize slowly fade away. You wonder if there is a solution to this disease of forgetting. I’ve got the solution to that. That solution, you may ask? It’s called spaced repetition.' },
      { type: 'heading', text: 'What is Spaced Repetition?' },
      { type: 'paragraph', text: 'At a basic level, spaced repetition is the concept of repeated studying spread out over extended periods of time. The brain’s memory improves when it is being adequately challenged.' },
      { type: 'paragraph', text: 'Likening it to a weightlifting analogy, the brain loves when it is given moderate weight to train with. Therefore, it is advantageous to train the brain by just slightly challenging it over time.' },
      { type: 'paragraph', text: 'Spaced repetition achieves this by recalling the information right as it slips out of the brain’s grasp. While the information is harder to remember, it puts good stress on the brain, allowing it to develop stronger synaptic structures, in turn giving better memory.' },
      { type: 'paragraph', text: 'For example, if I were to learn something, and then wait until I was about to forget it, and then recall the information again, I would remember it even better than I did the first time.' },
      { type: 'heading', text: 'How Do We Implement This?' },
      { type: 'paragraph', text: 'At its simplest, the easiest way to implement spaced repetition is through taking very dense study sessions and widening them out. For example, if you are planning a five hour study session in two weeks, instead divide it into five one hour study sessions throughout the upcoming time.' },
      { type: 'paragraph', text: 'Either you can plan it out on your own, or use websites that facilitate the process for you.' },
      { type: 'heading', text: 'The Danger Zone (⚠️)' },
      { type: 'paragraph', text: 'If you aren’t experienced in the field or don’t know too much about memory, here is a key piece of advice: Let the algorithms figure it out. People have already sculpted algorithms that have modeled human retention very successfully.' },
      { type: 'paragraph', text: 'If you don’t follow their algorithms, it is very likely you can end up doing more harm than good in your studying. If you choose to facilitate your own spaced repetition in your studying, here is the big thing you should worry about: The Forgetting Curve.' },
      { type: 'image', src: 'https://substackcdn.com/image/fetch/$s_!Te0F!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3c1e7c42-01af-4c0f-8c92-8eff402d43be_1398x1288.png', alt: 'Forgetting curve example' },
      { type: 'paragraph', text: 'Ideally, in spaced repetition, you want to review when your retention is between 50% and 70%, as it allows your brain to work hard while not overloading it.' },
      { type: 'paragraph', text: 'Let’s assume here that you studied the information again when your retention was at 60%.' },
      { type: 'image', src: 'https://substackcdn.com/image/fetch/$s_!lg6w!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F6a5dab69-fbd9-4f44-a722-1519a6778ae6_1393x1322.png', alt: 'Retention black line example' },
      { type: 'paragraph', text: 'According to research, your retention would look like the black line here: After 1 and 2 days, your retention is 83 and 69 percent, respectively. That’s only after one round of spaced repetition.' },
      { type: 'paragraph', text: 'If you take anything from this post, let it be this: Stop cramming. Start spacing. Spaced repetition isn’t just a study trick—it’s a memory upgrade.' },
      { type: 'paragraph', text: 'Imagine what it could do for your grades, your language learning, or your lifelong knowledge. Try spacing your next study session and let me know how it goes.' },
      { type: 'quote', text: '—The Study Mission' },
    ],
  },
  {
    id: 3,
    title: 'The Psychological Trick That Separates Top Students',
    author: 'Derek Turso',
    readTime: '1 min read',
    date: 'September 21, 2025',
    icon: '/images/article-icons/icon3.svg',
    cardImage: '/images/articleicons/images.png',
    excerpt: 'How much effort do you really have to put in to get what you want?',
    content: [
      { type: 'paragraph', text: 'You know that feeling.' },
      { type: 'paragraph', text: 'The daunting power of the tasks ahead. Bearing down on you, pressuring you constantly. You think: I can’t possibly make a dent in this.' },
      { type: 'paragraph', text: 'However, that’s just what you think. While the hardest part is just starting, it’s often the most beneficial. And the Pareto Principle boosts this even further.' },
      { type: 'heading', text: 'But What Is It?' },
      { type: 'paragraph', text: 'The Pareto Principle, in itself, is the idea that 80% of gains come from 20% of the work given.' },
      { type: 'paragraph', text: 'In fractions, 4/5 of your results come from 1/5 the total work. What this really means: just by starting, you already get most of the results.' },
      { type: 'paragraph', text: 'Those big tasks that you are faced with can often be chipped down just by beginning the process.' },
      { type: 'paragraph', text: 'Think about writing an essay. In theory, writing a draft is the easy part, and revising is the long part. Now think about studying for a math test.' },
      { type: 'paragraph', text: 'Knowing the concepts is 80% of it, knowing those concepts at high depth is the long part.' },
      { type: 'heading', text: 'Why Does This Work?' },
      { type: 'paragraph', text: 'The Pareto Principle is heavily based on the concept of diminishing returns.' },
      { type: 'paragraph', text: 'The efficiency of your work greatly decreases over time—so the beginning of a task yields the most benefit.' },
      { type: 'heading', text: 'So, How Do We Use It?' },
      { type: 'paragraph', text: 'Use it to model how much work you truly have left and to budget your time: simple tasks often take much less time than you fear.' },
      { type: 'paragraph', text: 'Think about tasks exponentially: 1 hour might give 60%, 2 hours 80%, 3 hours 90%—so begin.' },
      { type: 'paragraph', text: 'I hope the Pareto Principle helps you start something big.' },
      { type: 'quote', text: '—The Study Mission' },
    ],
  },
];

export default articles;
